### ISSUE TITLE
clean up after failed install

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/datacats#29]
As we've been using datacats ourselves, we have a number of blind spots from the perspective of a brand new user. We want `datacats` to be a joy to use compared to the usual CKAN workflow, so we need to work on these.

Here's a workflow on a brand new Ubuntu machine. I've gotten past #28 and installed the right version of docker as well as datacats, and now I'm ready to go...

```
$ datacats create test
Creating environment "test"...Traceback (most recent call last):
  File "/usr/local/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.1', 'console_scripts', 'datacats')()
  File "/root/datacats/datacats/cli/main.py", line 111, in main
    return command_fn(opts)
  File "/root/datacats/datacats/cli/create.py", line 67, in create
    fn()
  File "/root/datacats/datacats/project.py", line 286, in create_virtualenv
    image=self._preload_image())
  File "/root/datacats/datacats/docker.py", line 87, in web_command
    detach=False)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.0.0-py2.7.egg/docker/client.py", line 425, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.0.0-py2.7.egg/docker/client.py", line 433, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.0.0-py2.7.egg/docker/client.py", line 99, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.0.0-py2.7.egg/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: datacats/web:preload_master (tag: preload_master)")
```

It looks like the images are missing on install. If a user pokes around, they might try fetching them:
```
datacats pull
Pulling image datacats/web........................................
Pulling image datacats/web:preload_master.....................
Pulling image datacats/postgres..........................t..
Pulling image datacats/solr..............
Pulling image scratch..{
  "errorDetail": {
    "message": "'scratch' is a reserved name"
  },
  "error": "'scratch' is a reserved name"
}

```

The "scratch" error is concerning, but let's keep going:
```
$ datacats create test
Environment data directory /root/.datacats/test already exists
```

Ok, I guess we have that environment already, but it didn't initialize properly and won't run. A little more investigation shows that I can `purge` it:

```
datacats purge test
Traceback (most recent call last):
  File "/usr/local/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.1', 'console_scripts', 'datacats')()
  File "/root/datacats/datacats/cli/main.py", line 111, in main
    return command_fn(opts)
  File "/root/datacats/datacats/cli/purge.py", line 40, in purge
    project.purge_data()
  File "/root/datacats/datacats/project.py", line 723, in purge_data
    rw={self.datadir: '/project/data'},
  File "/root/datacats/datacats/docker.py", line 96, in web_command
    raise WebCommandError(command, c['Id'][:12])
datacats.docker.WebCommandError: Command failed: ['/bin/rm', '-r', '/project/data/files', '/project/data/solr', '/project/data/postgres', '/project/data/venv']
  View output: docker logs 6c0346445655
  Remove stopped container: docker rm 6c0346445655
```

Ok, that didn't work but let's see what the log output is:

```
$ docker logs 6c03
/bin/rm: cannot remove '/project/data/solr': No such file or directory
/bin/rm: cannot remove '/project/data/postgres': No such file or directory
```

If I haven't given up by now, I probably will here. A user may now poke around the source of `datacats` and figure to delete the .environment directory:

```
$ cd ~/.datacats
$ rm -rf test/
```

Let's delete the source directory to and start fresh:
```
$ cd ~/environments/
$ rm -rf test/
```

Now let's try again:
```
$ datacats create test
```

Bingo!

This is a pretty terrible experience for a brand new user, so we still have work to do. I think most of this falls into:
- Better documentation
- Better error handling on commands, making sure we don't leave files around when `datacats create` fails, which causes subsequent commands to fail because `create` didn't finish properly
- Better error messages when something goes wrong. For example, if `create` fails with "No such image", we should provide a message to try `datacats pull`

**Comment by wardi** [comment]
Closing because a number of these issues have been resolved. please open separate issues for 'create fails' and other remaining separate issues
