### ISSUE TITLE
Issue with shell

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/datacats#45]
```
(donneesqc)Stephanes-MBP:donneesqctheme steph$ datacats shell
Traceback (most recent call last):
  File "/Users/steph/Documents/Projets/donneesqc/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.4', 'console_scripts', 'datacats')()
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/cli/main.py", line 115, in main
    return command_fn(project, opts)
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/cli/shell.py", line 19, in shell
    return project.interactive_shell(opts['COMMAND'])
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/project.py", line 664, in interactive_shell
    'datacats/web', '/scripts/shell.sh'] + command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by wardi** [comment]
should be fixed by f81a88b Please reopen if the issue persists
