### ISSUE TITLE
ConnectionError on OSX with 0.9dev1 (current master)

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/datacats#60]
```
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.9dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/cli/main.py", line 40, in <module>
    from datacats.cli import create, manage, install, pull, purge, shell, deploy
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/cli/create.py", line 11, in <module>
    from datacats.project import Project, ProjectError
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/project.py", line 22, in <module>
    from datacats.docker import (web_command, run_container, remove_container,
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/docker.py", line 30, in <module>
    _version_client.version()['ApiVersion'])
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.1.0-py2.7.egg/docker/client.py", line 943, in version
    return self._result(self._get(url), json=True)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.1.0-py2.7.egg/docker/client.py", line 103, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by wardi** [comment]
fixed by 1e0f6569f95d5e7
