### ISSUE TITLE
docker 1.6 incompatibility

### ISSUE THREAD

**Issue by wardi** [boxkite/datacats#73]
```python-traceback
(venv)ian@moby3:~/environments/test3$ datacats start
Traceback (most recent call last):
  File "/home/ian/boxkite/venv/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.9dev1', 'console_scripts', 'datacats')()
  File "/home/ian/boxkite/git/datacats/datacats/cli/main.py", line 114, in main
    return command_fn(environment, opts)
  File "/home/ian/boxkite/git/datacats/datacats/cli/manage.py", line 52, in start
    reload_(environment, opts)
  File "/home/ian/boxkite/git/datacats/datacats/cli/manage.py", line 76, in reload_
    environment.start_postgres_and_solr()
  File "/home/ian/boxkite/git/datacats/datacats/environment.py", line 387, in start_postgres_and_solr
    ro={self.target + '/schema.xml': '/etc/solr/conf/schema.xml'})
  File "/home/ian/boxkite/git/datacats/datacats/docker.py", line 152, in run_container
    ports=list(port_bindings) if port_bindings else None)
  File "/home/ian/boxkite/venv/local/lib/python2.7/site-packages/docker/client.py", line 463, in create_container
    return self.create_container_from_config(config, name)
  File "/home/ian/boxkite/venv/local/lib/python2.7/site-packages/docker/client.py", line 471, in create_container_from_config
    return self._result(res, True)
  File "/home/ian/boxkite/venv/local/lib/python2.7/site-packages/docker/client.py", line 123, in _result
    self._raise_for_status(response)
  File "/home/ian/boxkite/venv/local/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("file exists at /var/lib/docker/aufs/mnt/b141a1ccea7ce6d79cdd121abcf8c167b82acac7320e0f7c4c4bad2ac345ef3a/etc/solr/conf/schema.xml, can't create volume there")
```

**Comment by wardi** [comment]
related: https://github.com/docker/docker-py/issues/546, https://github.com/docker/docker/issues/12759
